name: publish.yml

on:
  push: 
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
  release:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore  
      - name: Publish
        run: |
          dotnet publish -c Release -r win-x64
          zip -j src/Chirp.CLI/bin/Release/net7.0/win-x64/publish/Chrip.CLI.zip src/Chirp.CLI/bin/Release/net7.0/win-x64/publish/Chrip.CLI.exe
          rm src/Chirp.CLI/bin/Release/net7.0/win-x64/publish/Chrip.CLI.exe
          rm src/Chirp.CLI/bin/Release/net7.0/win-x64/publish/SimpleDB.pdb
          
          dotnet publish -c Release -r linux-x64
          tar -czf src/Chirp.CLI/bin/Release/net7.0/linux-x64/publish/Chrip.CLI.tar.gz -C src/Chirp.CLI/bin/Release/net7.0/linux-x64/publish Chrip.CLI
          rm src/Chirp.CLI/bin/Release/net7.0/linux-x64/publish/Chrip.CLI
          rm src/Chirp.CLI/bin/Release/net7.0/linux-x64/publish/SimpleDB.pdb

          dotnet publish -c Release -r osx-x64
          zip -j src/Chirp.CLI/bin/Release/net7.0/osx-x64/publish/Chrip.CLI.zip src/Chirp.CLI/bin/Release/net7.0/osx-x64/publish/Chrip.CLI
          rm src/Chirp.CLI/bin/Release/net7.0/osx-x64/publish/Chrip.CLI
          rm src/Chirp.CLI/bin/Release/net7.0/osx-x64/publish/SimpleDB.pdb

          dotnet publish -c Release -r osx-arm64
          zip -j src/Chirp.CLI/bin/Release/net7.0/osx-arm64/publish/Chrip.CLI.zip src/Chirp.CLI/bin/Release/net7.0/osx-arm64/publish/Chrip.CLI
          rm src/Chirp.CLI/bin/Release/net7.0/osx-arm64/publish/Chrip.CLI
          rm src/Chirp.CLI/bin/Release/net7.0/osx-arm64/publish/SimpleDB.pdb