name: publish.yml

on:
  push: 
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: |
          cd src/Chirp.Web
          dotnet publish -c Release -o ./publish
      - name: Zip folder
        run: zip -r src/Chirp.Web/publish
        
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "src/Chirp.web/publish.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove zip and publish folder
        run: |
          rm src/Chirp.web/publish.zip
          rm -r src/Chirp.web/publish
          
