name: publish.yml

on:
  push: 
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      
      - name: Publish
        run: |
          export authentication_github_clientId="${{ secrets.GITHUBCLIENTID }}"
          export authentication_github_clientSecrets="${{ secrets.GITHUBCLIENTSECRET }}"
          dotnet publish src/Chirp.Web -c Release -o ./publish
        
      - name: Zip folder
        run: zip -r publish.zip ./publish/Chirp.Web.dll
        
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "publish.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
