name: publish.yml

on:
  push: 
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: |
          cd src/Chirp.Web
          dotnet publish -c Release -o ./publish
      - name: Zip folder
        run: zip -r src/Chirp.Web/publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Chirp-Web-Release
          path: src/Chirp.Web/publish.zip
        
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Chirp.Web-Release
      
      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "Release generated by GitHub Actions."
          draft: false
          prerelease: false
          
